using Microsoft.Extensions.Configuration;
using Without.Systems.Comprehend.Structures;

namespace Without.Systems.Comprehend.Test;

public class Tests
{
    private static readonly IComprehend _actions = new Comprehend();
    private Credentials _credentials;
    private readonly string _awsRegion = "eu-central-1";

    [SetUp]
    public void Setup()
    {
        IConfiguration configuration = new ConfigurationBuilder()
            .AddUserSecrets<Tests>()
            .AddEnvironmentVariables()
            .Build();

        string awsAccessKey = configuration["AWSAccessKey"] ?? throw new InvalidOperationException();
        string awsSecretAccessKey = configuration["AWSSecretAccessKey"] ?? throw new InvalidOperationException();
        
        _credentials = new Credentials(awsAccessKey,awsSecretAccessKey);
    }

    [Test]
    public void DetectDominantLanguage_English()
    {
        string text =
            "We are excited to announce that Knowledge Bases for Amazon Bedrock (KB) now lets you configure inference parameters to have greater control over personalizing the responses generated by a foundation model (FM).";
        var result = _actions.DetectDominantLanguage(_credentials, _awsRegion, text);
        Assert.That(result.FirstOrDefault().LanguageCode, Is.EqualTo("en"));
    }
}